import styles from "./User.module.css";
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useUser } from "../../hooks/useUser";

import { db, storage } from "../../data/firebase";
import { collection, getDocs, query, where, updateDoc, doc } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";

export default function User() {
  const { user, userIsLoading } = useUser();
  const navigate = useNavigate();

  const [imagePreview, setImagePreview] = useState(null);
  const [userData, setUserData] = useState({
    name: "",
    email: "",
    phoneNum: "",
    carrera: "",
    carnet: ""
  });

  useEffect(() => {
    if (!userIsLoading && user.email) {
      setUserData({
        name: user.name || "",
        email: user.email || "",
        phoneNum: user.phoneNum || "",
        carrera: user.carrera || "",
        carnet: user.carnet || ""
      });
    }
  }, [user, userIsLoading]);

 
  
  const handleChange = (e) => {
    const { name, value } = e.target;
    setUserData({ ...userData, [name]: value });
  };
  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    console.log("Selected file:", file); // Log the selected file object
    if (file && file.type === "image/png") {
      const reader = new FileReader();
      reader.onload = (e) => {
        console.log("FileReader result:", e.target.result); // Log the data URL generated by FileReader
        setImagePreview(e.target.result); // Set imagePreview to the base64 data URL
      };
      reader.readAsDataURL(file);
      console.log("Image type:", file.type); // Log the image type
    } else {
      alert("Please select a PNG file.");
      // Optionally, you can reset the file input field to clear the selection
      event.target.value = null;
    }
  };
  
  
  const updateUser = async () => {
    try {
      // Generate unique image ID
      const timestamp = new Date().getTime();
      const imageId = timestamp + '_' + imagePreview.name;
  
      // Upload image to Firebase Storage
      const storageRef = ref(storage, `user_images/${user.email}/${imageId}`);
      await uploadBytes(storageRef, imagePreview, { contentType: 'image/png' });
  
      // Get the download URL of the uploaded image
      const imageURL = await getDownloadURL(storageRef);
  
      // Update user data in Firestore with the image URL and other information
      const userDocRef = doc(db, "users", user.uid);
      await updateDoc(userDocRef, {
        imageURL: imageURL,
        name: userData.name,
        email: userData.email,
        phoneNum: userData.phoneNum,
        carrera: userData.carrera,
        carnet: userData.carnet
      });
  
      console.log("Image uploaded successfully and user data updated!");
  
    } catch (error) {
      console.error("Error updating user information:", error);
    }
  };
  
  if (userIsLoading) {
    return <p>Loading...</p>;
  }

  return (
    <div className={styles.userCard}>
      <div className={styles.leftside}>
        <img
          className={styles.image}
          src={imagePreview ? imagePreview : "./src/assets/userPage.png"}
          alt=""
        />
        <div>
          <label htmlFor="upload-btn" className={styles.uploadButton}>
            Cambiar imágen
          </label>
          <input
            type="file"
            id="upload-btn"
            onChange={handleFileUpload}
            accept="image/png" // Accept only PNG files
            hidden
          />
        </div>
        <button
          type="button"
          className={styles.submitBtn}
          onClick={updateUser}
        >
          Guardar cambios
        </button>
      </div>

      <div className={styles.rightside}>
        <div className={styles.titles}>
          <h1>Datos Personales</h1>
        </div>
        <div className={styles.text}>
          <div className={styles.inputContainer}>
            <label htmlFor="name">
              <span>Nombre</span>
            </label>
            <input
              type="text"
              name="name"
              id="name"
              placeholder="Ex. Andrea Linares"
              value={userData.name}
              onChange={handleChange}
            />
          </div>
          <div className={styles.inputContainer}>
          <label htmlFor="email">
              <span>Correo electrónico*</span>
            </label>
          <div className={styles.information}>
            
              <p className={styles.txt}>{userData.email}</p>
            
            </div>
          </div>

          <div className={styles.inputContainer}>
            <label htmlFor="phoneNum">
              <span>Número de Teléfono</span>
            </label>
            <input
              type="number"
              name="phoneNum"
              id="phoneNum"
              placeholder="Ex. 04121122345"
              value={userData.phoneNum}
              onChange={handleChange}
            />
          </div>

          <div className={styles.inputContainer}>
            <label htmlFor="carrera">
              <span>Carrera</span>
            </label>
            <input
              type="text"
              name="carrera"
              id="carrera"
              placeholder="Ex. Ingeniería Eléctrica"
              value={userData.carrera}
              onChange={handleChange}
            />
          </div>

          <div className={styles.inputContainer}>
            <label htmlFor="carnet">
              <span>Carnet</span>
            </label>
            <input
              type="number"
              name="carnet"
              id="carnet"
              placeholder="Ex. 202221110405"
              value={userData.carnet}
              onChange={handleChange}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
